### ISSUE TITLE
`AssertionError: View function mapping is overwriting an existing endpoint function: root`

### ISSUE THREAD

**Issue by bwesterb** [softdevteam/mattermost-github-integration#38]
```
Traceback (most recent call last):
  File "mattermostgithub/server.py", line 17, in <module>
    @app.route(config.SERVER['hook'] or "/", methods=['POST'])
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1080, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1051, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: root
```

I'm at 92394f236a81b9e4e7bca173d92e22458880c89c

**Comment by ptersilie** [comment]
@bwesterb Sorry for the late reply. Are you still running into this issue?

**Comment by bwesterb** [comment]
Haven't tried it again.
